### PR TITLE
Parameters integration

### PR DESCRIPTION
**Pull request by devtrack**
Here is the parameters integration. I don't do much on customization, not good with that.

### CODE REVIEW

**Comment by artemavrin** [comment]
hello @devtrack! thank you!
I think if dialogue parameters are global for all phrases in ShowPhrases node it will be a bit better. What do you think?

**Comment by devtrack** [comment]
Yes good idea. In that way, you can even introduce a node "context" that setup a context at execution (FFormatNamedArguments) where all children showphrases and questions would take their formatting. That mean a new node, and a recursive interface function, or something else, for looking for his first "context" parent.

**Comment by artemavrin** [comment]
yeah! it's even better) so we don't need dialogue parameters in each question and phrase nodes) I definitely like it :smile:
I'm going to close this PR. Can you create a new PR with new node (I think it should be a composite node)? I just want you become a contributor with this code) it's your idea
-OR-
I'll create a commit with referense to this PR
what do you prefer?

**Comment by devtrack** [comment]
I am currently on dialogue by the way, and i need context for my game (dont want to put parameters for each phrase), so i integrate this and put a new PR ;)

**Comment by artemavrin** [comment]
nice) see you in next PR :smile:

**Pull request closed without merging**
